[build]
  # Comando de build
  command = "npm run build"
  
  # Directorio donde se encuentran los archivos construidos
  publish = "dist"
  
  # Directorio base (en caso de que el proyecto esté en una subcarpeta)
  base = "."

[build.environment]
  # Variables de entorno para el build
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Redirecciones para SPA (Single Page Application)
# Esta configuración es CRÍTICA para evitar errores 404
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  
# Redirecciones específicas para API (si las tienes)
[[redirects]]
  from = "/api/*"
  to = "https://gogestiaapi.onrender.com/api/:splat"
  status = 200
  force = true

# Headers de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://gogestiaapi.onrender.com"

# Headers para archivos estáticos (caché)
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers para el index.html (no cachear)
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache"
